# docker-compose.local.yml

version: "3.9"

services:
  sdlc-agent:
    container_name: sdlc-agent-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    working_dir: /app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped