version: "3.9"

services:
  web:
    build: .
    ports:
      - "8001:8000"  # Host port 8001 → Container port 8000 (to avoid clash with dev/prod)
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    restart: unless-stopped
    # 🔥 REMOVE port binding to prevent clash with other redis services
    # ports:
    #   - "6379:6379"