version: "3.9"

services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-8000}:8000"  # Use 8000 if WEB_PORT not defined
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"  # Optional: use different redis ports
    restart: unless-stopped