import argparse
import os
from src.services.llm_ticket_generator import generate_jira_tickets_from_requirements


def read_markdown_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def main():
    parser = argparse.ArgumentParser(description="Generate Jira stories and tasks from a structured feature requirement.")
    parser.add_argument("--file", required=True, help="Path to the markdown requirement file.")
    parser.add_argument("--model", default="gpt-4", help="OpenAI model to use (default: gpt-4)")

    args = parser.parse_args()

    if not os.path.exists(args.file):
        print(f"❌ Error: File not found: {args.file}")
        return

    markdown = read_markdown_file(args.file)
    print("\n📦 Generating Jira ticket data...\n")
    result = generate_jira_tickets_from_requirements(markdown, model=args.model)

    if result:
        print("✅ Output:\n")
        print(result)
    else:
        print("⚠️ No content generated by LLM.")

if __name__ == "__main__":
    main()