name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Ensure Staging target directory exists
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p '${{ secrets.TARGET_DIR_STAGING }}'"

      - name: Copy code to EC2 (Staging)
        run: |
          rsync -az -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:'${{ secrets.TARGET_DIR_STAGING }}'

      - name: Copy .env to EC2 (Staging)
        run: |
          echo "${{ secrets.ENV_FILE_STAGING }}" > .env
          rsync -az -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" .env \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:'${{ secrets.TARGET_DIR_STAGING }}/.env'
          rm .env

      - name: Deploy on Staging EC2
        run: |
          ssh -tt -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            echo "📁 Switching to target dir"
            cd '${{ secrets.TARGET_DIR_STAGING }}'
            
            echo "🔧 Adjusting ports in docker-compose.yml"
            sed -i 's/"8000:8000"/"8001:8000"/' docker-compose.yml || true
            
            echo "🧹 Bringing down existing containers"
            docker-compose -p staging down || true
            
            echo "🏗️ Rebuilding containers"
            docker-compose -p staging_project build
            
            echo "🚀 Starting containers"
            docker-compose -p staging_project up -d
            
            echo "✅ Staging deployment completed"
          EOF